#+title: leaf-convert.el
#+author: Naoya Yamashita

[[https://github.com/conao3/leaf-convert.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/leaf-convert.el.png]]

[[https://github.com/conao3/leaf-convert.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/leaf-convert.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-convert.el/releases][https://img.shields.io/github/tag/conao3/leaf-convert.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-convert.el/actions][https://github.com/conao3/leaf-convert.el/workflows/Main%20workflow/badge.svg]]

* Overview

Convert plain Emacs Lisp or ~use-package~ declarations into ~leaf~ expressions.

Rather than simply translating ~use-package~ keywords, this package expands the source to plain Elisp first, then converts it to ~leaf~. This approach can produce cleaner ~leaf~ expressions, though forms without corresponding keywords will be placed in the ~:config~ section.

You can also run ~leaf~ expressions through the converter to optimize and reorganize them with appropriate keywords.

* Requirements

- Emacs 26.1 or later
- [[https://github.com/conao3/leaf.el][leaf]] 3.6.0 or later
- [[https://github.com/conao3/leaf-keywords.el][leaf-keywords]] 1.1.0 or later
- [[https://github.com/conao3/ppp.el][ppp]] 2.1 or later

* Installation

Install from MELPA:

#+begin_src emacs-lisp
(leaf leaf-convert :ensure t)
#+end_src

* Usage

Pass any S-expressions to ~leaf-convert~ to get the corresponding ~leaf~ form.

** Converting key bindings

#+begin_src emacs-lisp
(leaf-convert
 (defvar leaf-covert-variable)
 (bind-key "C-c x" 'my-ctrl-c-x-command)
 (bind-key "C-c x" 'my-ctrl-c-x-command some-other-mode-map)
 (bind-keys :map dired-mode-map
            ("o" . dired-omit-mode)
            ("a" . some-custom-dired-function)))

;; Result:
;; (leaf leaf-convert
;;   :defvar leaf-covert-variable
;;   :bind (("C-c x" . my-ctrl-c-x-command)
;;          (some-other-mode-map
;;           ("C-c x" . my-ctrl-c-x-command))
;;          (dired-mode-map
;;           ("o" . dired-omit-mode)
;;           ("a" . some-custom-dired-function))))
#+end_src

** Converting use-package declarations

#+begin_src emacs-lisp
(leaf-convert
 (use-package edit-server
   :if window-system
   :init
   (add-hook 'after-init-hook 'server-start t)
   (add-hook 'after-init-hook 'edit-server-start t)))

;; Result:
;; (leaf edit-server
;;   :when window-system
;;   :hook ((after-init-hook . server-start)
;;          (after-init-hook . edit-server-start))
;;   :require t)
#+end_src

** Optimizing existing leaf expressions

#+begin_src emacs-lisp
(leaf-convert
 (leaf markdown-mode
   :config
   (with-eval-after-load 'markdown-mode
     (require 'org-table)
     (add-hook 'markdown-mode-hook 'orgtbl-mode)
     (unbind-key "`" gfm-mode-map)
     (visual-line-mode nil))))

;; Result:
;; (leaf markdown-mode
;;   :after t
;;   :hook ((markdown-mode-hook . orgtbl-mode))
;;   :require org-table
;;   :config
;;   (unbind-key "`" gfm-mode-map)
;;   (visual-line-mode nil))
#+end_src

* Supported Keywords

The following ~leaf~ keywords are supported for automatic conversion:

| Keyword          | Status                        |
|------------------+-------------------------------|
| ~:load-path~     | Supported                     |
| ~:load-path*~    | Supported                     |
| ~:defun~         | Supported                     |
| ~:defvar~        | Supported                     |
| ~:preface~       | Supported                     |
| ~:when~          | Supported                     |
| ~:unless~        | Supported                     |
| ~:if~            | Converted to ~:when/:unless~  |
| ~:package~       | Converted to ~:ensure~        |
| ~:ensure~        | Supported                     |
| ~:after~         | Supported                     |
| ~:commands~      | Supported                     |
| ~:bind~          | Supported                     |
| ~:bind*~         | Supported                     |
| ~:mode~          | Supported                     |
| ~:interpreter~   | Supported                     |
| ~:magic~         | Supported                     |
| ~:magic-fallback~| Supported                     |
| ~:hook~          | Supported                     |
| ~:init~          | Supported                     |
| ~:custom~        | Supported                     |
| ~:custom*~       | Supported                     |
| ~:custom-face~   | Supported                     |
| ~:require~       | Supported                     |
| ~:chord~         | Supported                     |
| ~:chord*~        | Supported                     |
| ~:config~        | Supported                     |
| ~:diminish~      | Supported                     |
| ~:delight~       | Supported                     |
| ~:setq~          | Supported                     |
| ~:setq-default~  | Supported                     |

* Contributing

Contributions are welcome. Please feel free to open issues or submit pull requests on [[https://github.com/conao3/leaf-convert.el][GitHub]].

** Development Setup

1. Clone the repository
2. Install [[https://github.com/cask/cask][Cask]] for dependency management
3. Run ~make~ to set up the development environment
4. Run ~make test~ to run the test suite

** Workflow

#+begin_src shell
git checkout -b feature-branch
# Make your changes
make test
git commit -am "Description of changes"
git push origin feature-branch
# Open a pull request
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/leaf-convert.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (C) 2020 Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
