#+author: conao3
#+date: <2018-10-25 Thu>

[[https://github.com/conao3/leaf-convert.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/leaf-convert.el.png]]
[[https://github.com/conao3/leaf-convert.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/leaf-convert.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-convert.el/releases][https://img.shields.io/github/tag/conao3/leaf-convert.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-convert.el/actions][https://github.com/conao3/leaf-convert.el/workflows/Main%20workflow/badge.svg]]
[[https://app.codacy.com/project/conao3/leaf-convert.el/dashboard][https://img.shields.io/codacy/grade/62a36f4f04524d5e8c758440e8071c45.svg?logo=codacy&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]
[[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][https://img.shields.io/badge/chat-on_slack-blue.svg?logo=slack&style=flat-square]]

* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#customize][Customize]]
- [[#syntaxes][Syntaxes]]
- [[#information][Information]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#migration][Migration]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]
  - [[#special-thanks][Special Thanks]]

* Description
#+begin_src emacs-lisp
  (leaf-available-keywords)
  ;;=> (:disabled
  ;;    :leaf-protect           ; <leaf system keyword>
  ;;    :load-path              ; supported!!
  ;;    :load-path*             ; supported!!
  ;;    :leaf-autoload          ; <leaf system keyword>
  ;;    :doc                    ; <leaf doc keyword>
  ;;    :req                    ; <leaf doc keyword>
  ;;    :tag                    ; <leaf doc keyword>
  ;;    :file                   ; <leaf doc keyword>
  ;;    :url                    ; <leaf doc keyword>
  ;;    :added                  ; <leaf doc keyword>
  ;;    :defun                  ; supported!!
  ;;    :defvar                 ; supported!!
  ;;    :leaf-defun             ; <leaf system keyword>
  ;;    :leaf-defvar            ; <leaf system keyword>
  ;;    :preface
  ;;    :when
  ;;    :unless
  ;;    :if
  ;;    :emacs<
  ;;    :emacs<=
  ;;    :emacs=
  ;;    :emacs>
  ;;    :emacs>=
  ;;    :package                ; <converted to :ensure>
  ;;    :ensure                 ; supported!!
  ;;    :feather                ; <no corresponding sexp>
  ;;    :straight
  ;;    :el-get
  ;;    :after
  ;;    :commands               ; supported!!
  ;;    :bind
  ;;    :bind*
  ;;    :mode
  ;;    :interpreter
  ;;    :magic
  ;;    :magic-fallback
  ;;    :hook
  ;;    :advice
  ;;    :advice-remove
  ;;    :init
  ;;    :pre-setq
  ;;    :pl-pre-setq
  ;;    :auth-pre-setq
  ;;    :custom
  ;;    :custom*
  ;;    :pl-custom
  ;;    :auth-custom
  ;;    :custom-face
  ;;    :require                ; supported!!
  ;;    :hydra
  ;;    :transient
  ;;    :combo
  ;;    :combo*
  ;;    :smartrep
  ;;    :smartrep*
  ;;    :chord
  ;;    :chord*
  ;;    :mode-hook
  ;;    :leaf-defer
  ;;    :config
  ;;    :global-minor-mode
  ;;    :diminish               ; supported!!
  ;;    :delight                ; supported!!
  ;;    :setq                   ; supported!!
  ;;    :setq-default           ; supoorted!!
  ;;    :pl-setq
  ;;    :auth-setq
  ;;    :pl-setq-default
  ;;    :auth-setq-default)
#+end_src

* Install
~leaf-convert~ is available via ~el-get~.

#+begin_src emacs-lisp
  (leaf leaf-convert :el-get conao3/leaf-convert)
#+end_src

* Usage
Please use ~leaf-convert~ and pass any sexp.

#+begin_src emacs-lisp
  (leaf-convert
   (add-to-list a "a"))
  ;;=> (leaf leaf-convert
  ;;     :config (add-to-list a "a"))
#+end_src

* Customize

* Information
** Community
All feedback and suggestions are welcome!

You can use github issues, but you can also use [[https://conao3-support.slack.com/join/shared_invite/enQtNjUzMDMxODcyMjE1LWUwMjhiNTU3Yjk3ODIwNzAxMTgwOTkxNmJiN2M4OTZkMWY0NjI4ZTg4MTVlNzcwNDY2ZjVjYmRiZmJjZDU4MDE][Slack]]
if you want a more casual conversation.

** Contribution
We welcome PR!

*** Require tools for testing
- cask
  - install via brew
    #+begin_src shell
      brew install cask
    #+end_src

  - manual install
    #+begin_src shell
      cd ~/
      hub clone cask/cask
      export PATH="$HOME/.cask/bin:$PATH"
    #+end_src

*** Running test
Below operation flow is recommended.
#+begin_src shell
  make                              # Install git-hooks in local .git

  git branch [feature-branch]       # Create branch named [feature-branch]
  git checkout [feature-branch]     # Checkout branch named [feature-branch]

  # <edit loop>
  emacs leaf-convert.el             # Edit something you want

  make test                         # Test leaf-convert via multi version Emacs
  git commit -am "brabra"           # Commit (auto-run test before commit)
  # </edit loop>

  hub fork                          # Create fork at GitHub
  git push [user] [feature-branch]  # Push feature-branch to your fork
  hub pull-request                  # Create pull-request
#+end_src

** Migration

** License
#+begin_example
  General Public License Version 3 (GPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/leaf-convert.el/blob/master/LICENSE
#+end_example

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
